#!/bin/bash
###################################
# Author: Ibrar Ansari
# Date: 23-04-2025
# Version: 1
#
# This is my profile script
###################################

### Installation steps
# nano ~/.bash_profile
# source ~/.bash_profile
alias reload='source ~/.bash_profile && source ~/.bashrc'

###################
##    Docker     ##
###################

function add_users_to_docker_group() {
  # Get a list of all manually created users
  users=$(awk -F':' '$3 >= 1000 && $1 != "nobody" { print $1 }' /etc/passwd)
  # Loop through the list of users
  for user in $users; do
    # Add the user to the "docker" group
    sudo usermod -aG docker $user
  done
}

install_docker() {
    cd /tmp/ && curl -fsSL https://get.docker.com -o get-docker.sh
    sudo sh get-docker.sh
    sudo groupadd docker
    add_users_to_docker_group
    sudo systemctl enable docker
    sudo systemctl restart docker
    echo ""
    echo "Reboot required so, kindly reboot system"
}

install_docker_compose() {
	sudo curl -L "https://github.com/docker/compose/releases/download/v2.26.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
	sudo chmod +x /usr/local/bin/docker-compose
	cp -a /usr/local/bin/docker-compose /usr/bin/docker-compose
    sudo apt-get install docker-compose-plugin >  /dev/null 2>&1
	docker-compose -v
    echo ""
    echo "Docker-compose installed!..."
}


alias dps="docker ps -a"
alias dpe='clear && docker ps -a -f "status=exited"'
alias dpi='clear >$(tty) && echo -e "List of running containers" && docker ps --format "table {{.ID}}\t{{.RunningFor}}\t{{.Status}}\t{{.Image}}\t{{.Names}}"'
alias dpp='clear >$(tty) && docker ps --format "table {{.ID}}\t{{.Names}}\t{{.Ports}}"'
alias dpia='clear >$(tty) && docker ps --format "table {{.Names}}\t{{.ID}}\t{{.Status}}\t{{.Ports}}\t{{.Image}}\t{{.Command}}\{{.RunningFor}}\{{.Status}}"'
alias dpl="docker pull $1"
alias dis="docker images"
alias drn="docker run -itd $1 $2"
alias dsp="docker stop $1"
alias dspa='docker stop $(docker ps -aq)'
alias dst="docker start $1"
alias drt="docker restart $1"
alias dre="docker rename $1"
alias dls="docker logs -fn 20 $1"
alias drm="docker rm $1 -f"
alias dri="docker rmi $1 -f"
alias dit="docker inspect $1"
alias dvl="docker volume ls"
alias dsd="docker system df -v"
alias dss="docker stats"
alias drs='docker rm $(docker ps -q -f status=exited) -f'
alias dhy="docker history $1"
alias ddi='docker rmi $(docker images --filter "dangling=true" -q --no-trunc)'
alias durn="docker update --restart=no $1"
alias dura="docker update --restart=always $1"
alias dcr="docker ps -aq | xargs docker inspect --format '{{.Name}} Restart: {{ .HostConfig.RestartPolicy.Name }}'"

dec() {
  docker exec -it "$@" bash
}

decx() {
  docker exec -it "$@" sh
}

dhp() {
	echo "dpl = docker pull"
	echo "dis = docker images"
	echo "drn = docker run -itd 2=name 2=image"
	echo "dps = docker ps -a"
	echo "dpi = Formatted by Ibrar"
	echo "dpp = Formatted ports"
	echo "dsp = docker stop"
    echo "dspa = docker stop All"
    echo "dst = docker start"
	echo "drt = docker restart"
	echo "dre = docker rename"
	echo "dec = docker exec -it"
	echo "dls = docker logs"
	echo "drm = docker rm -f"
	echo "dri = docker rmi -f"
	echo "dit = docker inspect"
	echo "dvl = docker volume ls"
	echo "dss = docker stats"
    echo "dsd = docker system df -v #==> Check disk space used by docker"
	echo "drs = docker rm $(docker ps -q -f status=exited)"
	echo "dhy = docker history"
	echo "ddi = docker rmi $(docker images --filter "dangling=true" -q --no-trunc)"
	echo "durn = docker update --restart=no <Container>"
    echo "dura = docker update --restart=always <Container>"
    echo "dcr = docker inspect restart policy"
}


###################
##    Docker  Compose   ##
###################
# Defined in the `docker-compose` plugin, please check there for details.
alias c=docker-compose "$@"
alias cb='docker-compose build'
alias cup='docker-compose up -d'
alias cr='docker-compose run --service-ports --rm'
alias crl='docker-compose run --service-ports --rm local'
alias crd='docker-compose run --service-ports --rm develop'
alias crt='docker-compose run --rm test'
alias crp='docker-compose run --rm provision'
alias crci='docker-compose run --rm ci'
alias crwt='docker-compose run --rm watchtest'
alias cps='docker-compose ps'
alias cls='docker-compose logs -f --tail 100'

crm(){
	docker-compose stop $1
	docker-compose rm --force $1
}

dup() {
    # Check if the new `docker compose` command exists by checking its version
    if docker compose version > /dev/null 2>&1; then
        # Use the newer 'docker compose' command
        #echo "Using 'docker compose up -d'"
        docker compose up -d
    elif docker-compose version > /dev/null 2>&1; then
        # Fallback to the older 'docker-compose' command
        #echo "Using 'docker-compose up -d'"
        docker-compose up -d
    else
        # If neither command is found
        echo "Error: Docker Compose not found!"
        return 1
    fi
}


ddown() {
    # Check if the new `docker compose` command exists by checking its version
    if docker compose version > /dev/null 2>&1; then
        # Use the newer 'docker compose' command
        #echo "Using 'docker compose down'"
        docker compose down
    elif docker-compose version > /dev/null 2>&1; then
        # Fallback to the older 'docker-compose' command
        #echo "Using 'docker-compose down'"
        docker-compose down
    else
        # If neither command is found
        echo "Error: Docker Compose not found!"
        return 1
    fi
}
